-- =============================================
-- Função: process_engagement_comments_with_claude v3
-- Descrição: Processa comentários de engajamento com Claude AI
-- Versão: v3 - Fix timestamps baixos ([00:00] - [00:14])
-- Data: 2025-10-26
-- Atualização: Fix crítico para evitar timestamps muito baixos
--
-- PROBLEMA RESOLVIDO:
-- - Mensagens com [0:00], [0:14] no projeto 117
-- - Transcrições têm timestamps de intro/vinheta [00:00]-[00:14]
-- - Claude estava usando timestamps muito baixos (não-naturais)
--
-- SOLUÇÃO (3 CAMADAS):
-- 1. PROMPT: Regra explícita "NEVER use < 00:15" + exemplos negativos
-- 2. VALIDAÇÃO SQL: Detecta timestamps baixos pós-Claude
-- 3. FILTRO: Remove timestamps < 00:15 da transcrição antes de enviar
--
-- Testado contra: Projeto 117, vídeo "I Tested 500+ AI Tools..."
-- =============================================

-- Ver arquivo completo em:
-- /Supabase/supabase/migrations/20251026000000_fix_low_timestamps_engagement_comments.sql

-- Esta é a migration aplicada em produção
-- Backup mantido para referência histórica
