version: '3.8'

services:
  youtube-search-engine:
    build: .
    container_name: liftlio-youtube-search
    ports:
      - "8000:8000"
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - PORT=8000
      - HOST=0.0.0.0
      - LOG_LEVEL=INFO
    volumes:
      - ./youtube_search_engine.py:/app/youtube_search_engine.py:ro
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - liftlio-network
    labels:
      - "com.liftlio.service=youtube-search"
      - "com.liftlio.version=1.0.0"

networks:
  liftlio-network:
    driver: bridge